"""fix_services_on_boxes' generated hardening script — byte-for-byte golden.

The service-hardening script RUNS ON LIVE BOXES and has been debugged through several
incidents, so the refactor that moved its per-service fragments into the module-level
SERVICE_FIXUPS table had to be provably output-neutral. This file is that proof: GOLDEN
is the exact text the PRE-REFACTOR `fix_services_on_boxes` produced (captured by
running the unmodified function with a stubbed ssh_via_gateway, which base64-decodes to
the script the box would receive), and the first test asserts the pure builder still
produces every case identically — not "line-equivalent", byte-identical.

Case matrix:
  * every catalog service keyword any branch keyed on (kw_*);
  * every aliased group, including the groups that are NOT aliases of each other
    (the apache gap-filler wants apache|httpd, the fedora named.conf block wants
    bind alone, the bind9 options block wants bind|named|dns);
  * a box with no services, a box with nothing but an unknown pin, and a box with
    all 19 keywords at once;
  * credlist sizes 0, 1 and 3 (mysql/postfix/dovecot interpolate the accounts);
  * dict-shaped per-pin overrides from box_services.json;
  * duplicate pins and a REVERSED pin list, which pins the output ORDER to
    SERVICE_FIXUP_ORDER rather than to the pin order.

Second gate: every generated script still parses under `sh -n` (same cheap real check
tests/test_non_apt_prep.py uses).
"""

import subprocess
import sys
import unittest
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO))
from hardening_ops import SERVICE_FIXUPS, SERVICE_FIXUP_ORDER, service_fixup_script

CREDS1 = {"medic": "p1"}
CREDS2 = {"medic": "p1", "ubuntu": "p2"}
CREDS3 = {"medic": "p1", "ubuntu": "p2", "root": "p3"}

ALL_KEYWORDS = ['apache', 'httpd', 'bind', 'mysql', 'mariadb', 'postfix', 'smtp', 'nginx', 'http', 'web', 'vsftpd', 'ftp', 'dovecot', 'imap', 'named', 'dns', 'telnet-service', 'telnet', 'splunk']

# name -> (pin list as it appears in box_services.json, creds)
CASES = {
    "kw_apache": (['apache'], CREDS2),
    "kw_httpd": (['httpd'], CREDS2),
    "kw_bind": (['bind'], CREDS2),
    "kw_mysql": (['mysql'], CREDS2),
    "kw_mariadb": (['mariadb'], CREDS2),
    "kw_postfix": (['postfix'], CREDS2),
    "kw_smtp": (['smtp'], CREDS2),
    "kw_nginx": (['nginx'], CREDS2),
    "kw_http": (['http'], CREDS2),
    "kw_web": (['web'], CREDS2),
    "kw_vsftpd": (['vsftpd'], CREDS2),
    "kw_ftp": (['ftp'], CREDS2),
    "kw_dovecot": (['dovecot'], CREDS2),
    "kw_imap": (['imap'], CREDS2),
    "kw_named": (['named'], CREDS2),
    "kw_dns": (['dns'], CREDS2),
    "kw_telnet_service": (['telnet-service'], CREDS2),
    "kw_telnet": (['telnet'], CREDS2),
    "kw_splunk": (['splunk'], CREDS2),
    "no_services": ([], CREDS2),
    "one_cred": (['nginx'], CREDS1),
    "three_creds": (['mysql', 'postfix', 'dovecot'], CREDS3),
    "empty_creds": (['nginx'], {}),
    "all_services": (['apache', 'httpd', 'bind', 'mysql', 'mariadb', 'postfix', 'smtp', 'nginx', 'http', 'web', 'vsftpd', 'ftp', 'dovecot', 'imap', 'named', 'dns', 'telnet-service', 'telnet', 'splunk'], CREDS3),
    "reverse_order": (['splunk', 'telnet', 'telnet-service', 'dns', 'named', 'imap', 'dovecot', 'ftp', 'vsftpd', 'web', 'http', 'nginx', 'smtp', 'postfix', 'mariadb', 'mysql', 'bind', 'httpd', 'apache'], CREDS2),
    "bind_and_named": (['bind', 'named'], CREDS2),
    "duplicate_pins": (['mysql', 'mysql', 'mariadb'], CREDS1),
    "dict_pins": ([{'name': 'nginx'}, {'name': 'mysql'}, 'splunk'], CREDS2),
    "smtp_mail_users": (['smtp'], CREDS3),
    "apache_group": (['apache', 'httpd'], CREDS2),
    "mysql_mariadb_group": (['mysql', 'mariadb'], CREDS2),
    "nginx_http_web_group": (['nginx', 'http', 'web'], CREDS2),
    "vsftpd_ftp_group": (['vsftpd', 'ftp'], CREDS2),
    "dovecot_imap_group": (['dovecot', 'imap'], CREDS2),
    "bind_named_dns_group": (['bind', 'named', 'dns'], CREDS2),
    "telnet_group": (['telnet-service', 'telnet'], CREDS2),
    "unknown_service": (['random-unknown'], CREDS2),
}

# name -> the exact script the pre-refactor code generated, as its line list. Joining
# the lines with newlines gives the bytes the box receives (split/join round-trips).
GOLDEN = {
    "kw_apache": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "if [ -d /var/www/html ] && [ ! -f /var/www/html/index.html ]; then echo '<html><body>tz</body></html>' | sudo tee /var/www/html/index.html >/dev/null; fi || true",
        "# httpd resolves its (unset) ServerName against DNS at boot and can hang when the resolver isn't up yet (pfsense-ad fedora member); localhost short-circuits that on every later boot",
        "if [ -d /etc/httpd/conf.d ] && [ ! -f /etc/httpd/conf.d/00-tzc-servername.conf ]; then echo 'ServerName localhost' | sudo tee /etc/httpd/conf.d/00-tzc-servername.conf >/dev/null; sudo systemctl restart httpd 2>/dev/null || true; fi || true",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_httpd": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "if [ -d /var/www/html ] && [ ! -f /var/www/html/index.html ]; then echo '<html><body>tz</body></html>' | sudo tee /var/www/html/index.html >/dev/null; fi || true",
        "# httpd resolves its (unset) ServerName against DNS at boot and can hang when the resolver isn't up yet (pfsense-ad fedora member); localhost short-circuits that on every later boot",
        "if [ -d /etc/httpd/conf.d ] && [ ! -f /etc/httpd/conf.d/00-tzc-servername.conf ]; then echo 'ServerName localhost' | sudo tee /etc/httpd/conf.d/00-tzc-servername.conf >/dev/null; sudo systemctl restart httpd 2>/dev/null || true; fi || true",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_bind": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "if [ -f /etc/named.conf ]; then sudo sed -i 's/listen-on port 53 { 127.0.0.1; };/listen-on port 53 { any; };/' /etc/named.conf; sudo sed -i 's/allow-query\\(.*\\) { localhost; };/allow-query\\1 { any; };/' /etc/named.conf; sudo mkdir -p /etc/systemd/resolved.conf.d; printf '[Resolve]\\nDNSStubListener=no\\n' | sudo tee /etc/systemd/resolved.conf.d/no-stub.conf >/dev/null; sudo systemctl restart systemd-resolved 2>/dev/null || true; sudo systemctl restart named 2>/dev/null || true; fi || true",
        "",
        "# Bind9: allow queries from anywhere",
        "sudo python3 -c \"import re; p='/etc/bind/named.conf.local'; \"\"s=open(p).read(); \"\"open(p,'w').write(re.sub(r'zone \\\"localhost\\\" \\{[^}]*\\};\\\\n?', '', s))\" 2>/dev/null || true",
        "cat > /tmp/named.conf.options << 'BIND9EOF'",
        "options {",
        "  directory \"/var/cache/bind\";",
        "  recursion yes;",
        "  allow-query { any; };",
        "  forwarders { 8.8.8.8; 1.1.1.1; };",
        "};",
        "BIND9EOF",
        "sudo cp /tmp/named.conf.options /etc/bind/named.conf.options",
        "if [ ! -f /etc/bind/named.conf.default-zones ]; then",
        "  cat > /tmp/named.conf.default-zones << 'BZEOF'",
        "zone \".\" {",
        "  type hint;",
        "  file \"/usr/share/dns/root.hints\";",
        "};",
        "zone \"localhost\" {",
        "  type master;",
        "  file \"/etc/bind/db.local\";",
        "};",
        "zone \"127.in-addr.arpa\" {",
        "  type master;",
        "  file \"/etc/bind/db.127\";",
        "};",
        "BZEOF",
        "  sudo cp /tmp/named.conf.default-zones /etc/bind/named.conf.default-zones",
        "fi",
        "if [ ! -f /etc/bind/db.local ]; then",
        "  cat > /tmp/db.local << 'DLEOF'",
        "$TTL 86400",
        "@   IN  SOA ns1.localhost. root.localhost. (",
        "        2026071201",
        "        3600",
        "        1800",
        "        604800",
        "        86400 )",
        "    IN  NS  ns1.localhost.",
        "ns1 IN  A   127.0.0.1",
        "@   IN  A   127.0.0.1",
        "DLEOF",
        "  sudo cp /tmp/db.local /etc/bind/db.local",
        "fi",
        "sudo systemctl restart bind9 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_mysql": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# MySQL/MariaDB: bind to 0.0.0.0",
        "# Try all possible config file locations",
        "for cnf in /etc/mysql/mysql.conf.d/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/my.cnf; do",
        "  if [ -f \"$cnf\" ]; then",
        "    sudo sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' \"$cnf\"",
        "  fi",
        "done",
        "sudo systemctl restart mysql 2>/dev/null || sudo systemctl restart mariadb 2>/dev/null || true",
        "sleep 2",
        "# Create MySQL users from credlist",
        "cat > /tmp/setup_mysql.sql << 'SQLEOF'",
        "CREATE USER IF NOT EXISTS 'medic'@'%' IDENTIFIED BY 'p1';",
        "GRANT ALL PRIVILEGES ON *.* TO 'medic'@'%' WITH GRANT OPTION;",
        "CREATE USER IF NOT EXISTS 'ubuntu'@'%' IDENTIFIED BY 'p2';",
        "GRANT ALL PRIVILEGES ON *.* TO 'ubuntu'@'%';",
        "FLUSH PRIVILEGES;",
        "SQLEOF",
        "chmod 600 /tmp/setup_mysql.sql",
        "sudo mysql < /tmp/setup_mysql.sql || true",
        "rm -f /tmp/setup_mysql.sql",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_mariadb": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# MySQL/MariaDB: bind to 0.0.0.0",
        "# Try all possible config file locations",
        "for cnf in /etc/mysql/mysql.conf.d/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/my.cnf; do",
        "  if [ -f \"$cnf\" ]; then",
        "    sudo sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' \"$cnf\"",
        "  fi",
        "done",
        "sudo systemctl restart mysql 2>/dev/null || sudo systemctl restart mariadb 2>/dev/null || true",
        "sleep 2",
        "# Create MySQL users from credlist",
        "cat > /tmp/setup_mysql.sql << 'SQLEOF'",
        "CREATE USER IF NOT EXISTS 'medic'@'%' IDENTIFIED BY 'p1';",
        "GRANT ALL PRIVILEGES ON *.* TO 'medic'@'%' WITH GRANT OPTION;",
        "CREATE USER IF NOT EXISTS 'ubuntu'@'%' IDENTIFIED BY 'p2';",
        "GRANT ALL PRIVILEGES ON *.* TO 'ubuntu'@'%';",
        "FLUSH PRIVILEGES;",
        "SQLEOF",
        "chmod 600 /tmp/setup_mysql.sql",
        "sudo mysql < /tmp/setup_mysql.sql || true",
        "rm -f /tmp/setup_mysql.sql",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_postfix": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Postfix: ensure it listens on all interfaces",
        "sudo postconf -e 'inet_interfaces = all' 2>/dev/null || true",
        "sudo postconf -e 'inet_protocols = ipv4' 2>/dev/null || true",
        "# Ensure smtpd listener exists (non-interactive install may leave master.cf empty).",
        "sudo postconf -M 'smtp/inet=smtp inet n - y - - smtpd' 2>/dev/null || true",
        "sudo systemctl restart postfix 2>/dev/null || true",
        "sleep 1",
        "# Create mail users matching credlist for SMTP checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_smtp": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Postfix: ensure it listens on all interfaces",
        "sudo postconf -e 'inet_interfaces = all' 2>/dev/null || true",
        "sudo postconf -e 'inet_protocols = ipv4' 2>/dev/null || true",
        "# Ensure smtpd listener exists (non-interactive install may leave master.cf empty).",
        "sudo postconf -M 'smtp/inet=smtp inet n - y - - smtpd' 2>/dev/null || true",
        "sudo systemctl restart postfix 2>/dev/null || true",
        "sleep 1",
        "# Create mail users matching credlist for SMTP checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_nginx": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Nginx: ensure it starts and listens on port 80",
        "sudo systemctl restart nginx 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_http": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Nginx: ensure it starts and listens on port 80",
        "sudo systemctl restart nginx 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_web": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Nginx: ensure it starts and listens on port 80",
        "sudo systemctl restart nginx 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_vsftpd": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Vsftpd: ensure anonymous is off, local users can login",
        "sudo sed -i 's/^#*anonymous_enable.*/anonymous_enable=NO/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*local_enable.*/local_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*write_enable.*/write_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo systemctl restart vsftpd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_ftp": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Vsftpd: ensure anonymous is off, local users can login",
        "sudo sed -i 's/^#*anonymous_enable.*/anonymous_enable=NO/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*local_enable.*/local_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*write_enable.*/write_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo systemctl restart vsftpd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_dovecot": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Dovecot: enable plaintext auth, create mail dirs",
        "sudo sed -i 's/^#*disable_plaintext_auth.*/disable_plaintext_auth = no/' /etc/dovecot/conf.d/10-auth.conf 2>/dev/null || true",
        "dovecot --version 2>/dev/null | grep -qE '^(2\\.[4-9]|[3-9]\\.)' && sudo bash -c \"echo 'auth_allow_cleartext = yes' > /etc/dovecot/conf.d/99-allow-plaintext.conf\" || true",
        "sudo mkdir -p /home/medic/mail",
        "sudo chmod 700 /home/medic/mail",
        "sudo chown medic:medic /home/medic/mail 2>/dev/null || true",
        "sudo mkdir -p /home/ubuntu/mail",
        "sudo chmod 700 /home/ubuntu/mail",
        "sudo chown ubuntu:ubuntu /home/ubuntu/mail 2>/dev/null || true",
        "sudo systemctl restart dovecot 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_imap": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Dovecot: enable plaintext auth, create mail dirs",
        "sudo sed -i 's/^#*disable_plaintext_auth.*/disable_plaintext_auth = no/' /etc/dovecot/conf.d/10-auth.conf 2>/dev/null || true",
        "dovecot --version 2>/dev/null | grep -qE '^(2\\.[4-9]|[3-9]\\.)' && sudo bash -c \"echo 'auth_allow_cleartext = yes' > /etc/dovecot/conf.d/99-allow-plaintext.conf\" || true",
        "sudo mkdir -p /home/medic/mail",
        "sudo chmod 700 /home/medic/mail",
        "sudo chown medic:medic /home/medic/mail 2>/dev/null || true",
        "sudo mkdir -p /home/ubuntu/mail",
        "sudo chmod 700 /home/ubuntu/mail",
        "sudo chown ubuntu:ubuntu /home/ubuntu/mail 2>/dev/null || true",
        "sudo systemctl restart dovecot 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_named": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Bind9: allow queries from anywhere",
        "sudo python3 -c \"import re; p='/etc/bind/named.conf.local'; \"\"s=open(p).read(); \"\"open(p,'w').write(re.sub(r'zone \\\"localhost\\\" \\{[^}]*\\};\\\\n?', '', s))\" 2>/dev/null || true",
        "cat > /tmp/named.conf.options << 'BIND9EOF'",
        "options {",
        "  directory \"/var/cache/bind\";",
        "  recursion yes;",
        "  allow-query { any; };",
        "  forwarders { 8.8.8.8; 1.1.1.1; };",
        "};",
        "BIND9EOF",
        "sudo cp /tmp/named.conf.options /etc/bind/named.conf.options",
        "if [ ! -f /etc/bind/named.conf.default-zones ]; then",
        "  cat > /tmp/named.conf.default-zones << 'BZEOF'",
        "zone \".\" {",
        "  type hint;",
        "  file \"/usr/share/dns/root.hints\";",
        "};",
        "zone \"localhost\" {",
        "  type master;",
        "  file \"/etc/bind/db.local\";",
        "};",
        "zone \"127.in-addr.arpa\" {",
        "  type master;",
        "  file \"/etc/bind/db.127\";",
        "};",
        "BZEOF",
        "  sudo cp /tmp/named.conf.default-zones /etc/bind/named.conf.default-zones",
        "fi",
        "if [ ! -f /etc/bind/db.local ]; then",
        "  cat > /tmp/db.local << 'DLEOF'",
        "$TTL 86400",
        "@   IN  SOA ns1.localhost. root.localhost. (",
        "        2026071201",
        "        3600",
        "        1800",
        "        604800",
        "        86400 )",
        "    IN  NS  ns1.localhost.",
        "ns1 IN  A   127.0.0.1",
        "@   IN  A   127.0.0.1",
        "DLEOF",
        "  sudo cp /tmp/db.local /etc/bind/db.local",
        "fi",
        "sudo systemctl restart bind9 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_dns": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Bind9: allow queries from anywhere",
        "sudo python3 -c \"import re; p='/etc/bind/named.conf.local'; \"\"s=open(p).read(); \"\"open(p,'w').write(re.sub(r'zone \\\"localhost\\\" \\{[^}]*\\};\\\\n?', '', s))\" 2>/dev/null || true",
        "cat > /tmp/named.conf.options << 'BIND9EOF'",
        "options {",
        "  directory \"/var/cache/bind\";",
        "  recursion yes;",
        "  allow-query { any; };",
        "  forwarders { 8.8.8.8; 1.1.1.1; };",
        "};",
        "BIND9EOF",
        "sudo cp /tmp/named.conf.options /etc/bind/named.conf.options",
        "if [ ! -f /etc/bind/named.conf.default-zones ]; then",
        "  cat > /tmp/named.conf.default-zones << 'BZEOF'",
        "zone \".\" {",
        "  type hint;",
        "  file \"/usr/share/dns/root.hints\";",
        "};",
        "zone \"localhost\" {",
        "  type master;",
        "  file \"/etc/bind/db.local\";",
        "};",
        "zone \"127.in-addr.arpa\" {",
        "  type master;",
        "  file \"/etc/bind/db.127\";",
        "};",
        "BZEOF",
        "  sudo cp /tmp/named.conf.default-zones /etc/bind/named.conf.default-zones",
        "fi",
        "if [ ! -f /etc/bind/db.local ]; then",
        "  cat > /tmp/db.local << 'DLEOF'",
        "$TTL 86400",
        "@   IN  SOA ns1.localhost. root.localhost. (",
        "        2026071201",
        "        3600",
        "        1800",
        "        604800",
        "        86400 )",
        "    IN  NS  ns1.localhost.",
        "ns1 IN  A   127.0.0.1",
        "@   IN  A   127.0.0.1",
        "DLEOF",
        "  sudo cp /tmp/db.local /etc/bind/db.local",
        "fi",
        "sudo systemctl restart bind9 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_telnet_service": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Telnet: enable disabled inetd entry and restart.",
        "sudo update-inetd --enable telnet 2>/dev/null || true",
        "sudo systemctl restart inetutils-inetd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_telnet": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Telnet: enable disabled inetd entry and restart.",
        "sudo update-inetd --enable telnet 2>/dev/null || true",
        "sudo systemctl restart inetutils-inetd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "kw_splunk": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Splunk: Nakon only creates user, need something on port 8000",
        "sudo apt-get install -y lighttpd 2>/dev/null || true",
        "sudo sed -i 's/server.port.*/server.port = 8000/' /etc/lighttpd/lighttpd.conf 2>/dev/null || true",
        "sudo systemctl enable lighttpd 2>/dev/null || true",
        "# restart, not start: lighttpd may already be running on :80 from the",
        "# plant \u2014 start is a no-op on an active unit and the port move never lands",
        "sudo systemctl restart lighttpd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "no_services": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "one_cred": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Nginx: ensure it starts and listens on port 80",
        "sudo systemctl restart nginx 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "three_creds": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu/root) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash root 2>/dev/null || true",
        "echo 'root:p3' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# MySQL/MariaDB: bind to 0.0.0.0",
        "# Try all possible config file locations",
        "for cnf in /etc/mysql/mysql.conf.d/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/my.cnf; do",
        "  if [ -f \"$cnf\" ]; then",
        "    sudo sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' \"$cnf\"",
        "  fi",
        "done",
        "sudo systemctl restart mysql 2>/dev/null || sudo systemctl restart mariadb 2>/dev/null || true",
        "sleep 2",
        "# Create MySQL users from credlist",
        "cat > /tmp/setup_mysql.sql << 'SQLEOF'",
        "CREATE USER IF NOT EXISTS 'medic'@'%' IDENTIFIED BY 'p1';",
        "GRANT ALL PRIVILEGES ON *.* TO 'medic'@'%' WITH GRANT OPTION;",
        "CREATE USER IF NOT EXISTS 'ubuntu'@'%' IDENTIFIED BY 'p2';",
        "GRANT ALL PRIVILEGES ON *.* TO 'ubuntu'@'%';",
        "CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'p3';",
        "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';",
        "FLUSH PRIVILEGES;",
        "SQLEOF",
        "chmod 600 /tmp/setup_mysql.sql",
        "sudo mysql < /tmp/setup_mysql.sql || true",
        "rm -f /tmp/setup_mysql.sql",
        "",
        "# Postfix: ensure it listens on all interfaces",
        "sudo postconf -e 'inet_interfaces = all' 2>/dev/null || true",
        "sudo postconf -e 'inet_protocols = ipv4' 2>/dev/null || true",
        "# Ensure smtpd listener exists (non-interactive install may leave master.cf empty).",
        "sudo postconf -M 'smtp/inet=smtp inet n - y - - smtpd' 2>/dev/null || true",
        "sudo systemctl restart postfix 2>/dev/null || true",
        "sleep 1",
        "# Create mail users matching credlist for SMTP checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash root 2>/dev/null || true",
        "echo 'root:p3' | sudo chpasswd",
        "",
        "# Dovecot: enable plaintext auth, create mail dirs",
        "sudo sed -i 's/^#*disable_plaintext_auth.*/disable_plaintext_auth = no/' /etc/dovecot/conf.d/10-auth.conf 2>/dev/null || true",
        "dovecot --version 2>/dev/null | grep -qE '^(2\\.[4-9]|[3-9]\\.)' && sudo bash -c \"echo 'auth_allow_cleartext = yes' > /etc/dovecot/conf.d/99-allow-plaintext.conf\" || true",
        "sudo mkdir -p /home/medic/mail",
        "sudo chmod 700 /home/medic/mail",
        "sudo chown medic:medic /home/medic/mail 2>/dev/null || true",
        "sudo mkdir -p /home/ubuntu/mail",
        "sudo chmod 700 /home/ubuntu/mail",
        "sudo chown ubuntu:ubuntu /home/ubuntu/mail 2>/dev/null || true",
        "sudo mkdir -p /home/root/mail",
        "sudo chmod 700 /home/root/mail",
        "sudo chown root:root /home/root/mail 2>/dev/null || true",
        "sudo systemctl restart dovecot 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "empty_creds": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts () for all auth-based service checks",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Nginx: ensure it starts and listens on port 80",
        "sudo systemctl restart nginx 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "all_services": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu/root) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash root 2>/dev/null || true",
        "echo 'root:p3' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "if [ -d /var/www/html ] && [ ! -f /var/www/html/index.html ]; then echo '<html><body>tz</body></html>' | sudo tee /var/www/html/index.html >/dev/null; fi || true",
        "# httpd resolves its (unset) ServerName against DNS at boot and can hang when the resolver isn't up yet (pfsense-ad fedora member); localhost short-circuits that on every later boot",
        "if [ -d /etc/httpd/conf.d ] && [ ! -f /etc/httpd/conf.d/00-tzc-servername.conf ]; then echo 'ServerName localhost' | sudo tee /etc/httpd/conf.d/00-tzc-servername.conf >/dev/null; sudo systemctl restart httpd 2>/dev/null || true; fi || true",
        "",
        "if [ -f /etc/named.conf ]; then sudo sed -i 's/listen-on port 53 { 127.0.0.1; };/listen-on port 53 { any; };/' /etc/named.conf; sudo sed -i 's/allow-query\\(.*\\) { localhost; };/allow-query\\1 { any; };/' /etc/named.conf; sudo mkdir -p /etc/systemd/resolved.conf.d; printf '[Resolve]\\nDNSStubListener=no\\n' | sudo tee /etc/systemd/resolved.conf.d/no-stub.conf >/dev/null; sudo systemctl restart systemd-resolved 2>/dev/null || true; sudo systemctl restart named 2>/dev/null || true; fi || true",
        "",
        "# MySQL/MariaDB: bind to 0.0.0.0",
        "# Try all possible config file locations",
        "for cnf in /etc/mysql/mysql.conf.d/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/my.cnf; do",
        "  if [ -f \"$cnf\" ]; then",
        "    sudo sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' \"$cnf\"",
        "  fi",
        "done",
        "sudo systemctl restart mysql 2>/dev/null || sudo systemctl restart mariadb 2>/dev/null || true",
        "sleep 2",
        "# Create MySQL users from credlist",
        "cat > /tmp/setup_mysql.sql << 'SQLEOF'",
        "CREATE USER IF NOT EXISTS 'medic'@'%' IDENTIFIED BY 'p1';",
        "GRANT ALL PRIVILEGES ON *.* TO 'medic'@'%' WITH GRANT OPTION;",
        "CREATE USER IF NOT EXISTS 'ubuntu'@'%' IDENTIFIED BY 'p2';",
        "GRANT ALL PRIVILEGES ON *.* TO 'ubuntu'@'%';",
        "CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'p3';",
        "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';",
        "FLUSH PRIVILEGES;",
        "SQLEOF",
        "chmod 600 /tmp/setup_mysql.sql",
        "sudo mysql < /tmp/setup_mysql.sql || true",
        "rm -f /tmp/setup_mysql.sql",
        "",
        "# Postfix: ensure it listens on all interfaces",
        "sudo postconf -e 'inet_interfaces = all' 2>/dev/null || true",
        "sudo postconf -e 'inet_protocols = ipv4' 2>/dev/null || true",
        "# Ensure smtpd listener exists (non-interactive install may leave master.cf empty).",
        "sudo postconf -M 'smtp/inet=smtp inet n - y - - smtpd' 2>/dev/null || true",
        "sudo systemctl restart postfix 2>/dev/null || true",
        "sleep 1",
        "# Create mail users matching credlist for SMTP checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash root 2>/dev/null || true",
        "echo 'root:p3' | sudo chpasswd",
        "",
        "# Nginx: ensure it starts and listens on port 80",
        "sudo systemctl restart nginx 2>/dev/null || true",
        "sleep 1",
        "",
        "# Vsftpd: ensure anonymous is off, local users can login",
        "sudo sed -i 's/^#*anonymous_enable.*/anonymous_enable=NO/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*local_enable.*/local_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*write_enable.*/write_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo systemctl restart vsftpd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Dovecot: enable plaintext auth, create mail dirs",
        "sudo sed -i 's/^#*disable_plaintext_auth.*/disable_plaintext_auth = no/' /etc/dovecot/conf.d/10-auth.conf 2>/dev/null || true",
        "dovecot --version 2>/dev/null | grep -qE '^(2\\.[4-9]|[3-9]\\.)' && sudo bash -c \"echo 'auth_allow_cleartext = yes' > /etc/dovecot/conf.d/99-allow-plaintext.conf\" || true",
        "sudo mkdir -p /home/medic/mail",
        "sudo chmod 700 /home/medic/mail",
        "sudo chown medic:medic /home/medic/mail 2>/dev/null || true",
        "sudo mkdir -p /home/ubuntu/mail",
        "sudo chmod 700 /home/ubuntu/mail",
        "sudo chown ubuntu:ubuntu /home/ubuntu/mail 2>/dev/null || true",
        "sudo mkdir -p /home/root/mail",
        "sudo chmod 700 /home/root/mail",
        "sudo chown root:root /home/root/mail 2>/dev/null || true",
        "sudo systemctl restart dovecot 2>/dev/null || true",
        "sleep 1",
        "",
        "# Bind9: allow queries from anywhere",
        "sudo python3 -c \"import re; p='/etc/bind/named.conf.local'; \"\"s=open(p).read(); \"\"open(p,'w').write(re.sub(r'zone \\\"localhost\\\" \\{[^}]*\\};\\\\n?', '', s))\" 2>/dev/null || true",
        "cat > /tmp/named.conf.options << 'BIND9EOF'",
        "options {",
        "  directory \"/var/cache/bind\";",
        "  recursion yes;",
        "  allow-query { any; };",
        "  forwarders { 8.8.8.8; 1.1.1.1; };",
        "};",
        "BIND9EOF",
        "sudo cp /tmp/named.conf.options /etc/bind/named.conf.options",
        "if [ ! -f /etc/bind/named.conf.default-zones ]; then",
        "  cat > /tmp/named.conf.default-zones << 'BZEOF'",
        "zone \".\" {",
        "  type hint;",
        "  file \"/usr/share/dns/root.hints\";",
        "};",
        "zone \"localhost\" {",
        "  type master;",
        "  file \"/etc/bind/db.local\";",
        "};",
        "zone \"127.in-addr.arpa\" {",
        "  type master;",
        "  file \"/etc/bind/db.127\";",
        "};",
        "BZEOF",
        "  sudo cp /tmp/named.conf.default-zones /etc/bind/named.conf.default-zones",
        "fi",
        "if [ ! -f /etc/bind/db.local ]; then",
        "  cat > /tmp/db.local << 'DLEOF'",
        "$TTL 86400",
        "@   IN  SOA ns1.localhost. root.localhost. (",
        "        2026071201",
        "        3600",
        "        1800",
        "        604800",
        "        86400 )",
        "    IN  NS  ns1.localhost.",
        "ns1 IN  A   127.0.0.1",
        "@   IN  A   127.0.0.1",
        "DLEOF",
        "  sudo cp /tmp/db.local /etc/bind/db.local",
        "fi",
        "sudo systemctl restart bind9 2>/dev/null || true",
        "sleep 1",
        "",
        "# Telnet: enable disabled inetd entry and restart.",
        "sudo update-inetd --enable telnet 2>/dev/null || true",
        "sudo systemctl restart inetutils-inetd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Splunk: Nakon only creates user, need something on port 8000",
        "sudo apt-get install -y lighttpd 2>/dev/null || true",
        "sudo sed -i 's/server.port.*/server.port = 8000/' /etc/lighttpd/lighttpd.conf 2>/dev/null || true",
        "sudo systemctl enable lighttpd 2>/dev/null || true",
        "# restart, not start: lighttpd may already be running on :80 from the",
        "# plant \u2014 start is a no-op on an active unit and the port move never lands",
        "sudo systemctl restart lighttpd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "reverse_order": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "if [ -d /var/www/html ] && [ ! -f /var/www/html/index.html ]; then echo '<html><body>tz</body></html>' | sudo tee /var/www/html/index.html >/dev/null; fi || true",
        "# httpd resolves its (unset) ServerName against DNS at boot and can hang when the resolver isn't up yet (pfsense-ad fedora member); localhost short-circuits that on every later boot",
        "if [ -d /etc/httpd/conf.d ] && [ ! -f /etc/httpd/conf.d/00-tzc-servername.conf ]; then echo 'ServerName localhost' | sudo tee /etc/httpd/conf.d/00-tzc-servername.conf >/dev/null; sudo systemctl restart httpd 2>/dev/null || true; fi || true",
        "",
        "if [ -f /etc/named.conf ]; then sudo sed -i 's/listen-on port 53 { 127.0.0.1; };/listen-on port 53 { any; };/' /etc/named.conf; sudo sed -i 's/allow-query\\(.*\\) { localhost; };/allow-query\\1 { any; };/' /etc/named.conf; sudo mkdir -p /etc/systemd/resolved.conf.d; printf '[Resolve]\\nDNSStubListener=no\\n' | sudo tee /etc/systemd/resolved.conf.d/no-stub.conf >/dev/null; sudo systemctl restart systemd-resolved 2>/dev/null || true; sudo systemctl restart named 2>/dev/null || true; fi || true",
        "",
        "# MySQL/MariaDB: bind to 0.0.0.0",
        "# Try all possible config file locations",
        "for cnf in /etc/mysql/mysql.conf.d/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/my.cnf; do",
        "  if [ -f \"$cnf\" ]; then",
        "    sudo sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' \"$cnf\"",
        "  fi",
        "done",
        "sudo systemctl restart mysql 2>/dev/null || sudo systemctl restart mariadb 2>/dev/null || true",
        "sleep 2",
        "# Create MySQL users from credlist",
        "cat > /tmp/setup_mysql.sql << 'SQLEOF'",
        "CREATE USER IF NOT EXISTS 'medic'@'%' IDENTIFIED BY 'p1';",
        "GRANT ALL PRIVILEGES ON *.* TO 'medic'@'%' WITH GRANT OPTION;",
        "CREATE USER IF NOT EXISTS 'ubuntu'@'%' IDENTIFIED BY 'p2';",
        "GRANT ALL PRIVILEGES ON *.* TO 'ubuntu'@'%';",
        "FLUSH PRIVILEGES;",
        "SQLEOF",
        "chmod 600 /tmp/setup_mysql.sql",
        "sudo mysql < /tmp/setup_mysql.sql || true",
        "rm -f /tmp/setup_mysql.sql",
        "",
        "# Postfix: ensure it listens on all interfaces",
        "sudo postconf -e 'inet_interfaces = all' 2>/dev/null || true",
        "sudo postconf -e 'inet_protocols = ipv4' 2>/dev/null || true",
        "# Ensure smtpd listener exists (non-interactive install may leave master.cf empty).",
        "sudo postconf -M 'smtp/inet=smtp inet n - y - - smtpd' 2>/dev/null || true",
        "sudo systemctl restart postfix 2>/dev/null || true",
        "sleep 1",
        "# Create mail users matching credlist for SMTP checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Nginx: ensure it starts and listens on port 80",
        "sudo systemctl restart nginx 2>/dev/null || true",
        "sleep 1",
        "",
        "# Vsftpd: ensure anonymous is off, local users can login",
        "sudo sed -i 's/^#*anonymous_enable.*/anonymous_enable=NO/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*local_enable.*/local_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*write_enable.*/write_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo systemctl restart vsftpd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Dovecot: enable plaintext auth, create mail dirs",
        "sudo sed -i 's/^#*disable_plaintext_auth.*/disable_plaintext_auth = no/' /etc/dovecot/conf.d/10-auth.conf 2>/dev/null || true",
        "dovecot --version 2>/dev/null | grep -qE '^(2\\.[4-9]|[3-9]\\.)' && sudo bash -c \"echo 'auth_allow_cleartext = yes' > /etc/dovecot/conf.d/99-allow-plaintext.conf\" || true",
        "sudo mkdir -p /home/medic/mail",
        "sudo chmod 700 /home/medic/mail",
        "sudo chown medic:medic /home/medic/mail 2>/dev/null || true",
        "sudo mkdir -p /home/ubuntu/mail",
        "sudo chmod 700 /home/ubuntu/mail",
        "sudo chown ubuntu:ubuntu /home/ubuntu/mail 2>/dev/null || true",
        "sudo systemctl restart dovecot 2>/dev/null || true",
        "sleep 1",
        "",
        "# Bind9: allow queries from anywhere",
        "sudo python3 -c \"import re; p='/etc/bind/named.conf.local'; \"\"s=open(p).read(); \"\"open(p,'w').write(re.sub(r'zone \\\"localhost\\\" \\{[^}]*\\};\\\\n?', '', s))\" 2>/dev/null || true",
        "cat > /tmp/named.conf.options << 'BIND9EOF'",
        "options {",
        "  directory \"/var/cache/bind\";",
        "  recursion yes;",
        "  allow-query { any; };",
        "  forwarders { 8.8.8.8; 1.1.1.1; };",
        "};",
        "BIND9EOF",
        "sudo cp /tmp/named.conf.options /etc/bind/named.conf.options",
        "if [ ! -f /etc/bind/named.conf.default-zones ]; then",
        "  cat > /tmp/named.conf.default-zones << 'BZEOF'",
        "zone \".\" {",
        "  type hint;",
        "  file \"/usr/share/dns/root.hints\";",
        "};",
        "zone \"localhost\" {",
        "  type master;",
        "  file \"/etc/bind/db.local\";",
        "};",
        "zone \"127.in-addr.arpa\" {",
        "  type master;",
        "  file \"/etc/bind/db.127\";",
        "};",
        "BZEOF",
        "  sudo cp /tmp/named.conf.default-zones /etc/bind/named.conf.default-zones",
        "fi",
        "if [ ! -f /etc/bind/db.local ]; then",
        "  cat > /tmp/db.local << 'DLEOF'",
        "$TTL 86400",
        "@   IN  SOA ns1.localhost. root.localhost. (",
        "        2026071201",
        "        3600",
        "        1800",
        "        604800",
        "        86400 )",
        "    IN  NS  ns1.localhost.",
        "ns1 IN  A   127.0.0.1",
        "@   IN  A   127.0.0.1",
        "DLEOF",
        "  sudo cp /tmp/db.local /etc/bind/db.local",
        "fi",
        "sudo systemctl restart bind9 2>/dev/null || true",
        "sleep 1",
        "",
        "# Telnet: enable disabled inetd entry and restart.",
        "sudo update-inetd --enable telnet 2>/dev/null || true",
        "sudo systemctl restart inetutils-inetd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Splunk: Nakon only creates user, need something on port 8000",
        "sudo apt-get install -y lighttpd 2>/dev/null || true",
        "sudo sed -i 's/server.port.*/server.port = 8000/' /etc/lighttpd/lighttpd.conf 2>/dev/null || true",
        "sudo systemctl enable lighttpd 2>/dev/null || true",
        "# restart, not start: lighttpd may already be running on :80 from the",
        "# plant \u2014 start is a no-op on an active unit and the port move never lands",
        "sudo systemctl restart lighttpd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "bind_and_named": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "if [ -f /etc/named.conf ]; then sudo sed -i 's/listen-on port 53 { 127.0.0.1; };/listen-on port 53 { any; };/' /etc/named.conf; sudo sed -i 's/allow-query\\(.*\\) { localhost; };/allow-query\\1 { any; };/' /etc/named.conf; sudo mkdir -p /etc/systemd/resolved.conf.d; printf '[Resolve]\\nDNSStubListener=no\\n' | sudo tee /etc/systemd/resolved.conf.d/no-stub.conf >/dev/null; sudo systemctl restart systemd-resolved 2>/dev/null || true; sudo systemctl restart named 2>/dev/null || true; fi || true",
        "",
        "# Bind9: allow queries from anywhere",
        "sudo python3 -c \"import re; p='/etc/bind/named.conf.local'; \"\"s=open(p).read(); \"\"open(p,'w').write(re.sub(r'zone \\\"localhost\\\" \\{[^}]*\\};\\\\n?', '', s))\" 2>/dev/null || true",
        "cat > /tmp/named.conf.options << 'BIND9EOF'",
        "options {",
        "  directory \"/var/cache/bind\";",
        "  recursion yes;",
        "  allow-query { any; };",
        "  forwarders { 8.8.8.8; 1.1.1.1; };",
        "};",
        "BIND9EOF",
        "sudo cp /tmp/named.conf.options /etc/bind/named.conf.options",
        "if [ ! -f /etc/bind/named.conf.default-zones ]; then",
        "  cat > /tmp/named.conf.default-zones << 'BZEOF'",
        "zone \".\" {",
        "  type hint;",
        "  file \"/usr/share/dns/root.hints\";",
        "};",
        "zone \"localhost\" {",
        "  type master;",
        "  file \"/etc/bind/db.local\";",
        "};",
        "zone \"127.in-addr.arpa\" {",
        "  type master;",
        "  file \"/etc/bind/db.127\";",
        "};",
        "BZEOF",
        "  sudo cp /tmp/named.conf.default-zones /etc/bind/named.conf.default-zones",
        "fi",
        "if [ ! -f /etc/bind/db.local ]; then",
        "  cat > /tmp/db.local << 'DLEOF'",
        "$TTL 86400",
        "@   IN  SOA ns1.localhost. root.localhost. (",
        "        2026071201",
        "        3600",
        "        1800",
        "        604800",
        "        86400 )",
        "    IN  NS  ns1.localhost.",
        "ns1 IN  A   127.0.0.1",
        "@   IN  A   127.0.0.1",
        "DLEOF",
        "  sudo cp /tmp/db.local /etc/bind/db.local",
        "fi",
        "sudo systemctl restart bind9 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "duplicate_pins": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# MySQL/MariaDB: bind to 0.0.0.0",
        "# Try all possible config file locations",
        "for cnf in /etc/mysql/mysql.conf.d/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/my.cnf; do",
        "  if [ -f \"$cnf\" ]; then",
        "    sudo sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' \"$cnf\"",
        "  fi",
        "done",
        "sudo systemctl restart mysql 2>/dev/null || sudo systemctl restart mariadb 2>/dev/null || true",
        "sleep 2",
        "# Create MySQL users from credlist",
        "cat > /tmp/setup_mysql.sql << 'SQLEOF'",
        "CREATE USER IF NOT EXISTS 'medic'@'%' IDENTIFIED BY 'p1';",
        "GRANT ALL PRIVILEGES ON *.* TO 'medic'@'%' WITH GRANT OPTION;",
        "FLUSH PRIVILEGES;",
        "SQLEOF",
        "chmod 600 /tmp/setup_mysql.sql",
        "sudo mysql < /tmp/setup_mysql.sql || true",
        "rm -f /tmp/setup_mysql.sql",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "dict_pins": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# MySQL/MariaDB: bind to 0.0.0.0",
        "# Try all possible config file locations",
        "for cnf in /etc/mysql/mysql.conf.d/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/my.cnf; do",
        "  if [ -f \"$cnf\" ]; then",
        "    sudo sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' \"$cnf\"",
        "  fi",
        "done",
        "sudo systemctl restart mysql 2>/dev/null || sudo systemctl restart mariadb 2>/dev/null || true",
        "sleep 2",
        "# Create MySQL users from credlist",
        "cat > /tmp/setup_mysql.sql << 'SQLEOF'",
        "CREATE USER IF NOT EXISTS 'medic'@'%' IDENTIFIED BY 'p1';",
        "GRANT ALL PRIVILEGES ON *.* TO 'medic'@'%' WITH GRANT OPTION;",
        "CREATE USER IF NOT EXISTS 'ubuntu'@'%' IDENTIFIED BY 'p2';",
        "GRANT ALL PRIVILEGES ON *.* TO 'ubuntu'@'%';",
        "FLUSH PRIVILEGES;",
        "SQLEOF",
        "chmod 600 /tmp/setup_mysql.sql",
        "sudo mysql < /tmp/setup_mysql.sql || true",
        "rm -f /tmp/setup_mysql.sql",
        "",
        "# Nginx: ensure it starts and listens on port 80",
        "sudo systemctl restart nginx 2>/dev/null || true",
        "sleep 1",
        "",
        "# Splunk: Nakon only creates user, need something on port 8000",
        "sudo apt-get install -y lighttpd 2>/dev/null || true",
        "sudo sed -i 's/server.port.*/server.port = 8000/' /etc/lighttpd/lighttpd.conf 2>/dev/null || true",
        "sudo systemctl enable lighttpd 2>/dev/null || true",
        "# restart, not start: lighttpd may already be running on :80 from the",
        "# plant \u2014 start is a no-op on an active unit and the port move never lands",
        "sudo systemctl restart lighttpd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "smtp_mail_users": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu/root) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash root 2>/dev/null || true",
        "echo 'root:p3' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Postfix: ensure it listens on all interfaces",
        "sudo postconf -e 'inet_interfaces = all' 2>/dev/null || true",
        "sudo postconf -e 'inet_protocols = ipv4' 2>/dev/null || true",
        "# Ensure smtpd listener exists (non-interactive install may leave master.cf empty).",
        "sudo postconf -M 'smtp/inet=smtp inet n - y - - smtpd' 2>/dev/null || true",
        "sudo systemctl restart postfix 2>/dev/null || true",
        "sleep 1",
        "# Create mail users matching credlist for SMTP checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash root 2>/dev/null || true",
        "echo 'root:p3' | sudo chpasswd",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "apache_group": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "if [ -d /var/www/html ] && [ ! -f /var/www/html/index.html ]; then echo '<html><body>tz</body></html>' | sudo tee /var/www/html/index.html >/dev/null; fi || true",
        "# httpd resolves its (unset) ServerName against DNS at boot and can hang when the resolver isn't up yet (pfsense-ad fedora member); localhost short-circuits that on every later boot",
        "if [ -d /etc/httpd/conf.d ] && [ ! -f /etc/httpd/conf.d/00-tzc-servername.conf ]; then echo 'ServerName localhost' | sudo tee /etc/httpd/conf.d/00-tzc-servername.conf >/dev/null; sudo systemctl restart httpd 2>/dev/null || true; fi || true",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "mysql_mariadb_group": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# MySQL/MariaDB: bind to 0.0.0.0",
        "# Try all possible config file locations",
        "for cnf in /etc/mysql/mysql.conf.d/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/my.cnf; do",
        "  if [ -f \"$cnf\" ]; then",
        "    sudo sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' \"$cnf\"",
        "  fi",
        "done",
        "sudo systemctl restart mysql 2>/dev/null || sudo systemctl restart mariadb 2>/dev/null || true",
        "sleep 2",
        "# Create MySQL users from credlist",
        "cat > /tmp/setup_mysql.sql << 'SQLEOF'",
        "CREATE USER IF NOT EXISTS 'medic'@'%' IDENTIFIED BY 'p1';",
        "GRANT ALL PRIVILEGES ON *.* TO 'medic'@'%' WITH GRANT OPTION;",
        "CREATE USER IF NOT EXISTS 'ubuntu'@'%' IDENTIFIED BY 'p2';",
        "GRANT ALL PRIVILEGES ON *.* TO 'ubuntu'@'%';",
        "FLUSH PRIVILEGES;",
        "SQLEOF",
        "chmod 600 /tmp/setup_mysql.sql",
        "sudo mysql < /tmp/setup_mysql.sql || true",
        "rm -f /tmp/setup_mysql.sql",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "nginx_http_web_group": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Nginx: ensure it starts and listens on port 80",
        "sudo systemctl restart nginx 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "vsftpd_ftp_group": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Vsftpd: ensure anonymous is off, local users can login",
        "sudo sed -i 's/^#*anonymous_enable.*/anonymous_enable=NO/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*local_enable.*/local_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo sed -i 's/^#*write_enable.*/write_enable=YES/' /etc/vsftpd.conf 2>/dev/null || true",
        "sudo systemctl restart vsftpd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "dovecot_imap_group": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Dovecot: enable plaintext auth, create mail dirs",
        "sudo sed -i 's/^#*disable_plaintext_auth.*/disable_plaintext_auth = no/' /etc/dovecot/conf.d/10-auth.conf 2>/dev/null || true",
        "dovecot --version 2>/dev/null | grep -qE '^(2\\.[4-9]|[3-9]\\.)' && sudo bash -c \"echo 'auth_allow_cleartext = yes' > /etc/dovecot/conf.d/99-allow-plaintext.conf\" || true",
        "sudo mkdir -p /home/medic/mail",
        "sudo chmod 700 /home/medic/mail",
        "sudo chown medic:medic /home/medic/mail 2>/dev/null || true",
        "sudo mkdir -p /home/ubuntu/mail",
        "sudo chmod 700 /home/ubuntu/mail",
        "sudo chown ubuntu:ubuntu /home/ubuntu/mail 2>/dev/null || true",
        "sudo systemctl restart dovecot 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "bind_named_dns_group": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "if [ -f /etc/named.conf ]; then sudo sed -i 's/listen-on port 53 { 127.0.0.1; };/listen-on port 53 { any; };/' /etc/named.conf; sudo sed -i 's/allow-query\\(.*\\) { localhost; };/allow-query\\1 { any; };/' /etc/named.conf; sudo mkdir -p /etc/systemd/resolved.conf.d; printf '[Resolve]\\nDNSStubListener=no\\n' | sudo tee /etc/systemd/resolved.conf.d/no-stub.conf >/dev/null; sudo systemctl restart systemd-resolved 2>/dev/null || true; sudo systemctl restart named 2>/dev/null || true; fi || true",
        "",
        "# Bind9: allow queries from anywhere",
        "sudo python3 -c \"import re; p='/etc/bind/named.conf.local'; \"\"s=open(p).read(); \"\"open(p,'w').write(re.sub(r'zone \\\"localhost\\\" \\{[^}]*\\};\\\\n?', '', s))\" 2>/dev/null || true",
        "cat > /tmp/named.conf.options << 'BIND9EOF'",
        "options {",
        "  directory \"/var/cache/bind\";",
        "  recursion yes;",
        "  allow-query { any; };",
        "  forwarders { 8.8.8.8; 1.1.1.1; };",
        "};",
        "BIND9EOF",
        "sudo cp /tmp/named.conf.options /etc/bind/named.conf.options",
        "if [ ! -f /etc/bind/named.conf.default-zones ]; then",
        "  cat > /tmp/named.conf.default-zones << 'BZEOF'",
        "zone \".\" {",
        "  type hint;",
        "  file \"/usr/share/dns/root.hints\";",
        "};",
        "zone \"localhost\" {",
        "  type master;",
        "  file \"/etc/bind/db.local\";",
        "};",
        "zone \"127.in-addr.arpa\" {",
        "  type master;",
        "  file \"/etc/bind/db.127\";",
        "};",
        "BZEOF",
        "  sudo cp /tmp/named.conf.default-zones /etc/bind/named.conf.default-zones",
        "fi",
        "if [ ! -f /etc/bind/db.local ]; then",
        "  cat > /tmp/db.local << 'DLEOF'",
        "$TTL 86400",
        "@   IN  SOA ns1.localhost. root.localhost. (",
        "        2026071201",
        "        3600",
        "        1800",
        "        604800",
        "        86400 )",
        "    IN  NS  ns1.localhost.",
        "ns1 IN  A   127.0.0.1",
        "@   IN  A   127.0.0.1",
        "DLEOF",
        "  sudo cp /tmp/db.local /etc/bind/db.local",
        "fi",
        "sudo systemctl restart bind9 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "telnet_group": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Telnet: enable disabled inetd entry and restart.",
        "sudo update-inetd --enable telnet 2>/dev/null || true",
        "sudo systemctl restart inetutils-inetd 2>/dev/null || true",
        "sleep 1",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ],
    "unknown_service": [
        "#!/bin/bash",
        "set -e",
        "",
        "# Credlist OS accounts (medic/ubuntu) for all auth-based service checks",
        "sudo useradd -m -s /bin/bash medic 2>/dev/null || true",
        "echo 'medic:p1' | sudo chpasswd",
        "sudo useradd -m -s /bin/bash ubuntu 2>/dev/null || true",
        "echo 'ubuntu:p2' | sudo chpasswd",
        "",
        "# Un-wedge sshd if a burst of ssh-* misconfig restarts tripped the start-limit",
        "sudo systemctl reset-failed ssh 2>/dev/null || true",
        "sudo systemctl is-active --quiet ssh || sudo systemctl start ssh 2>/dev/null || true",
        "",
        "# Ensure all installed services are running",
        "for svc in mysql mariadb postfix nginx vsftpd dovecot bind9 lighttpd apache2; do",
        "  if systemctl list-unit-files \"$svc.service\" &>/dev/null; then",
        "    sudo systemctl start $svc 2>/dev/null || true",
        "  fi",
        "done"
    ]
}


class GoldenBytes(unittest.TestCase):
    def test_case_matrix_matches_the_golden(self):
        self.assertEqual(set(CASES), set(GOLDEN),
                         "a case was added/removed without re-capturing the golden")

    def test_generated_script_is_byte_identical(self):
        for name, (services, creds) in CASES.items():
            with self.subTest(case=name):
                self.assertEqual(service_fixup_script(services, creds),
                                 "\n".join(GOLDEN[name]))

    def test_every_case_covers_only_known_keywords(self):
        # A keyword with no trigger anywhere means a fixup got dropped from
        # SERVICE_FIXUPS; the golden would then just encode the omission.
        triggers = {t for fixup in SERVICE_FIXUPS.values() for t in fixup.triggers}
        for name, (services, _creds) in CASES.items():
            for svc in services:
                svc = svc if isinstance(svc, str) else svc["name"]
                if svc in ALL_KEYWORDS:
                    self.assertIn(svc, triggers, f"{name}: {svc} has no fixup")

    def test_generated_script_parses_under_sh(self):
        for name, (services, creds) in CASES.items():
            with self.subTest(case=name):
                r = subprocess.run(["/bin/sh", "-n"], input=service_fixup_script(services, creds),
                                   capture_output=True, text=True, timeout=30)
                self.assertEqual(r.returncode, 0, f"{name}: {r.stderr}")


class TableShape(unittest.TestCase):
    def test_order_and_table_keys_agree(self):
        # Both directions: a group in the table but not the order would be silently
        # never emitted; one in the order but not the table would KeyError.
        self.assertEqual(set(SERVICE_FIXUP_ORDER), set(SERVICE_FIXUPS))
        self.assertEqual(len(SERVICE_FIXUP_ORDER), len(set(SERVICE_FIXUP_ORDER)))

    def test_aliases_are_data(self):
        # The aliasing that used to be a hand-written `or` chain, now a table.
        expected = {
            "apache": ("apache", "httpd"),
            "bind_named_conf": ("bind",),
            "mysql": ("mysql", "mariadb"),
            "postfix": ("postfix", "smtp"),
            "nginx": ("nginx", "http", "web"),
            "vsftpd": ("vsftpd", "ftp"),
            "dovecot": ("dovecot", "imap"),
            "bind9": ("bind", "named", "dns"),
            "telnet": ("telnet-service", "telnet"),
            "splunk": ("splunk",),
        }
        self.assertEqual({n: f.triggers for n, f in SERVICE_FIXUPS.items()}, expected)

    def test_every_fixup_has_exactly_one_source(self):
        for name, fixup in SERVICE_FIXUPS.items():
            with self.subTest(fixup=name):
                self.assertNotEqual(bool(fixup.lines), fixup.build is not None,
                                    "set exactly one of lines/build")

    def test_canonical_names_match_their_keys(self):
        # Copy-pasting a table entry and forgetting to rename it would otherwise leave
        # two groups answering to different keys but the same label.
        for key, fixup in SERVICE_FIXUPS.items():
            self.assertEqual(fixup.name, key)

    def test_builder_is_pure_and_deterministic(self):
        a = service_fixup_script(["bind", "mysql"], CREDS2)
        b = service_fixup_script(["bind", "mysql"], CREDS2)
        self.assertEqual(a, b)
        self.assertTrue(a.startswith("#!/bin/bash\nset -e\n"))
        self.assertFalse(a.endswith("\n"), "join() must not add a trailing newline")


class Ordering(unittest.TestCase):
    def test_bind_emits_named_conf_before_bind9_options(self):
        # Two different groups key on `bind`; their relative order is output, not a
        # preference. A reorder here silently changes what a live box runs.
        script = service_fixup_script(["bind"], CREDS2)
        self.assertLess(script.index("if [ -f /etc/named.conf ]"),
                        script.index("# Bind9: allow queries from anywhere"))

    def test_output_order_follows_the_table_not_the_pin_order(self):
        forward = service_fixup_script(ALL_KEYWORDS, CREDS2)
        reverse = service_fixup_script(list(reversed(ALL_KEYWORDS)), CREDS2)
        self.assertEqual(forward, reverse)


class CredlistAccounts(unittest.TestCase):
    def test_accounts_appear_once_without_the_postfix_branch(self):
        script = service_fixup_script(["nginx"], CREDS2)
        self.assertEqual(script.count("sudo useradd -m -s /bin/bash medic 2>/dev/null || true"), 1)

    def test_postfix_still_re_asserts_the_accounts(self):
        # The pre-refactor postfix branch carried its own copy of the useradd/chpasswd
        # pair; that duplicate is IN the golden, so the refactor deduplicated the
        # GENERATOR (_credlist_account_lines), not the emitted lines.
        script = service_fixup_script(["postfix"], CREDS2)
        self.assertEqual(script.count("sudo useradd -m -s /bin/bash medic 2>/dev/null || true"), 2)
        self.assertEqual(script.count("echo 'medic:p1' | sudo chpasswd"), 2)

    def test_empty_creds_still_yields_a_runnable_script(self):
        script = service_fixup_script(["mysql", "postfix", "dovecot"], {})
        self.assertIn("# Credlist OS accounts () for all auth-based service checks", script)
        self.assertEqual(subprocess.run(["/bin/sh", "-n"], input=script,
                                        capture_output=True, text=True).returncode, 0)


if __name__ == "__main__":
    unittest.main()
